/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Preference = IDL.Record({
  'playbackSpeed' : IDL.Float64,
  'accentColor' : IDL.Text,
  'apiKey' : IDL.Text,
});

export const idlService = IDL.Service({
  'createPreference' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [], []),
  'deletePreference' : IDL.Func([], [], []),
  'getAllPreferences' : IDL.Func([], [IDL.Vec(Preference)], ['query']),
  'getPreference' : IDL.Func([], [IDL.Opt(Preference)], ['query']),
  'updatePreference' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Preference = IDL.Record({
    'playbackSpeed' : IDL.Float64,
    'accentColor' : IDL.Text,
    'apiKey' : IDL.Text,
  });
  
  return IDL.Service({
    'createPreference' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [], []),
    'deletePreference' : IDL.Func([], [], []),
    'getAllPreferences' : IDL.Func([], [IDL.Vec(Preference)], ['query']),
    'getPreference' : IDL.Func([], [IDL.Opt(Preference)], ['query']),
    'updatePreference' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };